config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flights, only: :index
  resources :bookings, only: [:new, :create, :show]
  root 'flights#index'
end

app/models/airport.rb
# == Schema Information
#
# Table name: airports
#
#  id         :bigint           not null, primary key
#  code       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Airport < ApplicationRecord
  validates :code, presence: true, uniqueness: true, length: { maximum: 3 }

  has_many :departing_flights, { class_name: :Flight, foreign_key: :from_airport_id }
  has_many :arriving_flights, { class_name: :Flight, foreign_key: :to_airport_id }

  before_save :upcase_code

  private
    def upcase_code
      code.upcase!
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  flight_id  :integer          not null
#
# Indexes
#
#  index_bookings_on_flight_id  (flight_id)
#

class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passenger_booking_details, inverse_of: :booking
  has_many :passengers, through: :passenger_booking_details
  accepts_nested_attributes_for :passengers

  def create_associated_passengers(passengers_attributes)
    if passengers_attributes.to_h.any? { |k, v| v[:name].blank? || v[:email].blank? }
      passengers_attributes.each do |key, passengers_attribute|
        self.passengers.build(name:  passengers_attribute[:name],
                               email: passengers_attribute[:email])
      end
    else
      self.save
      passengers_attributes.each do |key, passengers_attribute|
        if passenger = Passenger.find_by(email: passengers_attribute[:email])
          self.passengers << passenger
        else
          self.passengers.create(name:  passengers_attribute[:name],
                                 email: passengers_attribute[:email])
        end
      end
    end
  end
end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id              :bigint           not null, primary key
#  duration        :integer          not null
#  start_datetime  :datetime         not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  from_airport_id :integer          not null
#  to_airport_id   :integer          not null
#

class Flight < ApplicationRecord
  validates :duration, presence: true
  validates :start_datetime, presence: true
  validate :ensure_different_start_and_finish

  belongs_to :from_airport, { class_name: :Airport, foreign_key: :from_airport_id }
  belongs_to :to_airport, { class_name: :Airport, foreign_key: :to_airport_id }
  has_many :bookings
  has_many :passengers, through: :bookings

  scope :search_criteria, ->(from_airport, to_airport, start_datetime, finish_datetime) do
    where("from_airport_id = ? AND
          to_airport_id = ? AND
          start_datetime >= ? AND
          start_datetime < ?",
          from_airport,
          to_airport,
          start_datetime,
          finish_datetime)
    .includes(:from_airport, :to_airport)
  end

  def date_formatted
    start_datetime.strftime("%d/%m/%Y at %I:%M %P")
  end

  def formatted_date_only
    start_datetime.strftime("%a, %dth %B, %Y")
  end

  def formatted_time_only
    start_datetime.strftime("%H:%M %p")
  end

  def display_journey
    "#{self.from_airport.code} to #{self.to_airport.code}"
  end

  private
    def ensure_different_start_and_finish
      errors.add(:start_and_finish, "can't be the same") if same_start_and_finish?
    end

    def same_start_and_finish?
      from_airport_id == to_airport_id
    end
end

app/models/passenger.rb
# == Schema Information
#
# Table name: passengers
#
#  id         :bigint           not null, primary key
#  email      :string           not null
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Passenger < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true

  has_many :passenger_booking_details
  has_many :bookings, through: :passenger_booking_details
  has_many :flights, through: :bookings
end

app/models/passenger_booking_detail.rb
# == Schema Information
#
# Table name: passenger_booking_details
#
#  id           :bigint           not null, primary key
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  booking_id   :integer          not null
#  passenger_id :integer          not null
#
# Indexes
#
#  index_passenger_booking_details_on_booking_id_and_passenger_id  (booking_id,passenger_id) UNIQUE
#  index_passenger_booking_details_on_passenger_id_and_booking_id  (passenger_id,booking_id)
#

class PassengerBookingDetail < ApplicationRecord
  validates :passenger_id, uniqueness: { scope: :booking_id,
                                         message: 'already has a booking on this flight' }

  belongs_to :booking
  belongs_to :passenger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    redirect_to request.referer and return if booking_params[:flight_id].nil?
    @booking = Booking.new(flight_id: booking_params[:flight_id])
    @flight_details = Flight.includes(:from_airport, :to_airport).find(booking_params[:flight_id])
    booking_params[:num_passengers].to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(flight_id: booking_params[:flight_id])
    @flight_details = Flight.includes(:from_airport, :to_airport).find(booking_params[:flight_id])
    @booking.create_associated_passengers(booking_params[:passengers_attributes])

    if !@booking.new_record?
      redirect_to @booking
      @booking.passengers.each do |passenger|
        PassengerMailer.with(passenger: passenger, booking: @booking).thank_you_email.deliver_later
      end
      return
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.includes(flight: [:from_airport, :to_airport])
                        .find(params[:id])
    @flight = @booking.flight
    @passengers = @booking.passengers
  end


  private
    def booking_params
      params.require(:booking).permit(:flight_id,
                                      :num_passengers,
                                      passengers_attributes: [:name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  include FlightsHelper

  def index
    @flights = Flight.all.includes(:from_airport, :to_airport)
    @airports = Airport.all.map { |a| [a.code, a.id] }
    @num_passengers = (1..4).map { |n| [n, n] }
    @flight_dates = @flights.map { |f| [f.date_formatted, f.start_datetime] }
    
    if !params[:flight].nil?
      @search_results = Flight.search_criteria(flight_params[:from_airport_id],
                                               flight_params[:to_airport_id],
                                               date_range_start(flight_params[:start_datetime]),
                                               date_range_end(flight_params[:start_datetime]))
      @selected_num_passengers = flight_params[:num_passengers]
    end
  end

  private
    def flight_params
      params.require(:flight).permit(:from_airport_id,
                                     :to_airport_id,
                                     :num_passengers,
                                     :start_datetime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  def date_range_start(date)
    start_date_as_integer = Time.zone.parse(date).to_i
    Time.zone.at(start_date_as_integer)
  end

  def date_range_end(date)
    end_date_as_integer = Time.zone.parse(date).to_i + 1
    Time.zone.at(end_date_as_integer)
  end

  def prefilled_flight_details(attr_name)
    params[:flight] ? params[:flight][attr_name] : nil
  end
end

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= form_for @booking do |f| %>
  <h3>Flight ID: <%= @booking.flight_id %></h2>
  <h3><%= "From: #{@flight_details.from_airport.code}" %></h2>
  <h3><%= "To: #{@flight_details.to_airport.code}" %></h2>
  <h3><%= "Date: #{@flight_details.formatted_date_only}" %></h2>
  <h3><%= "Time: #{@flight_details.formatted_time_only}" %></h2>

  <%= f.hidden_field(:flight_id) %>

  <h3>Passengers:</h3>
  <ul>
    <%= f.fields_for :passengers do |passengers_form| %>
      <li>
        <%= passengers_form.label :name %>
        <%= passengers_form.text_field :name %>

        <%= passengers_form.label :email %>
        <%= passengers_form.email_field :email %>
      </li>
    <% end %>
  </ul>

  <%= f.submit "Create Booking" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking <%= @booking.id %> Details</h1>

<h2>Flight Information</h2>
<ul>
  <li><%= "Flight ID: #{@flight.id}" %></li>
  <li><%= "From: #{@flight.from_airport.code}" %></li>
  <li><%= "To: #{@flight.to_airport.code}" %></li>
  <li><%= "Date: #{@flight.formatted_date_only}" %></li>
  <li><%= "Time: #{@flight.formatted_time_only}" %></li>
</ul>

<h2>Passenger Information</h2>
<% @passengers.each do |passenger| %>
  <ul>
    <li><%= "Name: #{passenger.name}" %></li>
    <li><%= "Email: #{passenger.email}" %></li>
  </ul>
<% end %>

app/views/flights/_search_form.html.erb
<%= form_for(:flight, url: flights_path, method: 'get') do |f| %>
  <%= f.label(:from_airport_id, "From Airport") %>
  <br>
  <%= f.select(:from_airport_id,
               options_for_select(airports,
               prefilled_flight_details(:from_airport_id))) %>

  <br>

  <%= f.label(:to_airport_id, "To Airport") %>
  <br>
  <%= f.select(:to_airport_id,
               options_for_select(airports,
               prefilled_flight_details(:to_airport_id))) %>

  <br>

  <%= f.label(:num_passengers, "Number of Passengers") %>
  <br>
  <%= f.select(:num_passengers,
               options_for_select(num_passengers,
               prefilled_flight_details(:num_passengers))) %>

  <br>

  <%= f.label(:start_datetime, "Date") %>
  <br>
  <%= f.select(:start_datetime,
               options_for_select(flight_dates,
               prefilled_flight_details(:start_datetime))) %>

  <br>
  <%= submit_tag("Search") %>
<% end %>

app/views/flights/_search_result_form.html.erb
<% if search_results %>
  <%= form_for(:booking, url: new_booking_url, method: 'get') do |f| %>
    <% search_results.each do |flight| %>
      <%= f.radio_button(:flight_id, flight.id) %>
      <%= f.label("flights_#{flight.id}".to_sym, flight.display_journey)  %>
    <% end %>

    <br>

    <%= f.hidden_field(:num_passengers, value: num_passengers)  %>

    <br>

    <% if search_results.any? %>
      <%= f.submit "Create Booking" %>
    <% end %>
  <% end %>
<% end %>

app/views/flights/index.html.erb
<h1>Search Flights</h1>
<%= render 'search_form', airports:       @airports,
                          num_passengers: @num_passengers,
                          flight_dates:   @flight_dates %>

<% if params[:flight] %>
  <h2>Search Results</h2>  
<% end %>                        
<%= render 'search_result_form', search_results: @search_results,
                                 num_passengers: @selected_num_passengers %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>